org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

# Fill these with your Baidu Speech API credentials before running on device.
BAIDU_APP_ID=123432768
BAIDU_API_KEY=kKPCNWbZBLN1LmDrpemOy00T
BAIDU_SECRET_KEY=CMeuCFEPJCBafn5tHWu0iaja8XUSJ6kJ
